[tool.black]
line-length = 79
target-version = ["py312"]
include = ".*\\.py$"
extend-exclude = "(venv|node_modules|__pycache__|migration_example)"

[tool.ruff]
target-version = "py312"
line-length = 79
extend-exclude = [
    "venv",
    "node_modules",
    "__pycache__",
    "migration_example",
]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort (import sorting)
    "UP"   # pyupgrade
]
ignore = [
    # allow prints in small app scripts
    "T201"
]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
line-ending = "lf"
